config/routes.rb
Rails.application.routes.draw do
  devise_for :agents
  devise_for :buyers, path: 'users'
  devise_for :admins
  
  resources :agents, only: [] do
    collection do
      resources :houses, as: :agents_houses
    end
  end

  resources :houses, only: [:index, :show]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
end

app/models/agent.rb
class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/house.rb
class House < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :validate_permission_to_create, only: [:new, :create]

  def index
    @houses = House.all
  end

  def new
    @house = House.new
  end

  def show
    @house = House.find(params[:id])
  end

  def create
    House.create!(params[:house])
  rescue
    redirect_to agents_houses_path, alert: 'Somethng wen wrong when creating the house! Try again, please.'
  end

  private

  def validate_permission_to_create
    redirect_to new_agent_session_path unless current_agent.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/houses/index.html.erb
<h2>Houses</h2>

<div class="row">
  <% @houses.each do |house| %>
    <%= link_to house_path(house.id) do %>
      <div class="col-md-4 col-xs-12 row">
        <div class="col-xs-12">
          <%= house.address %>
        </div>
        <div class="col-xs-12">
          <%= number_to_currency(house.price, unit: 'CAD$') %>
        </div>
        <div class="col-xs-12">
          <%= house.description %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/houses/new.html.erb
<%= form_for @house, url: '/agents/houses' do |f| %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <%= f.text_field :address, placeholder: 'Address' %>
    </div>

    <div class="col-xs-12 col-md-6">
      <%= f.number_field :price, placeholder: 'Price' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-6">
      <%= f.text_area :description, placeholder: 'Description', rows: 10 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 offset-md-10 col-md-2">
      <%= f.submit 'Put it on sale!', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/houses/show.html.erb
<div class="row">
  <div class="col-md-4 col-xs-12 row">
    <!-- TODO add images for the houses. Carousel, maybe? -->
    <div class="col-xs-12">
      <%= @house.address %>
    </div>
    <div class="col-xs-12">
      <%= number_to_currency(@house.price, unit: 'CAD$') %>
    </div>
    <div class="col-xs-12">
      <%= @house.description %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Come By.er</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row layout-banner">
      <div class="container">
        <%= link_to houses_path do %>
          <h1>ComeBy.er</h1>
        <% end %>
      </div>
    </div>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <div class="body">
        <%= yield %>
      </div>
    </div>
  </body>
</html>